print("Введите ширину поверхности в метрах:")
шир = float(input())
print("Введите высоту поверхности в метрах:")
выс = float(input())
print("Введите расход краски кв.м/л:")
расх = float(input())
print("Введите объём одной банки краски в литрах:")
об = float(input())
print("Введите запас краски:")
зап = float(input())
S = round(float(шир * выс), 2)
litr = round(float((S / расх) + ((S / расх) * (зап / 100))), 2)
bank = int((litr / об) + 1)
ost = round(float((bank * об) - litr), 2)
print(S)
print(litr)
print(bank)
print(ost)
